### ISSUE TITLE
When playing a song of a long artist, a crash message will be displayed.

### ISSUE THREAD

**Issue by book000** [nint8835/iTunesRichPresence#10]
A `System.ArgumentException` occurs when playing a song with a long artist name.

```
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at iTunesRichPresence.DiscordRPC.RichPresence.StrClampBytes(String toclamp, Int32 maxbytes)
   at iTunesRichPresence.DiscordRPC.RichPresence.StrToPtr(String input, Int32 maxbytes)
   at iTunesRichPresence.DiscordRPC.RichPresence.GetStruct()
   at iTunesRichPresence.DiscordRPC.UpdatePresence(RichPresence presence)
   at iTunesRichPresence.MainForm.UpdatePresence()
   at iTunesRichPresence.MainForm.pollTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
The corresponding song is below.

- Title: `うまるん体操`
  - Artist: `妹S(シスターズ)[土間うまる(CV:田中あいみ)/海老名菜々(CV:影山 灯)/本場切絵(CV:白石晴香)/橘・シルフィンフォード(CV:古川由利奈)]`
  - Album: `TVアニメ「干物妹!うまるちゃんR」EDテーマ「うまるん体操」 - EP`
- TItle: `メモワール・ミルフィーユ`
  - Artist: `キュアホイップ (美山加恋), キュアカスタード (福原遥), キュアジェラート (村中知), キュアマカロン (藤田咲), キュアショコラ (森なな子), キュアパルフェ (水瀬いのり)`
  - Album: `映画 キラキラ☆プリキュアアラモード パリッと! 想い出のミルフィーユ! 主題歌シングル`

ApplicationVersion: v1.2.2 (Latest release)

I like this application very much and using it. Thank you for your consideration.

**Comment by book000** [comment]
My prediction is because the length of newstrbytes in DiscordRPC.cs line 187 is 0?
`var newstrbytes = new byte[] { };` -> `var newstrbytes = new byte[maxbytes];`

**Comment by nint8835** [comment]
Just realized that I was shortening the artist and album name to the length limit, but then appending "..."
 to the end. The size limit should now be fixed so this crash does not happen in future releases.

**Comment by book000** [comment]
Uh…
I downloaded and executed v1.3.0, but System.ArgumentException occurred in the same way...

```
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at iTunesRichPresence.DiscordRPC.RichPresence.StrClampBytes(String toclamp, Int32 maxbytes)
   at iTunesRichPresence.DiscordRPC.RichPresence.StrToPtr(String input, Int32 maxbytes)
   at iTunesRichPresence.DiscordRPC.RichPresence.GetStruct()
   at iTunesRichPresence.DiscordRPC.UpdatePresence(RichPresence presence)
   at iTunesRichPresence.MainForm.UpdatePresence()
   at iTunesRichPresence.MainForm.pollTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
